clear_messages:
  cron: '0 0 0 * * *' # 0:0:0 everyday
  # every: 1 week
  class: ClearMessagesJob
  queue: low
  args: 
  description: 'This job clear non-applied messages from the past 3rd week, and clear all messages from the past month'