# ADMIN
User.find_or_create_by(
    id: 1, 
    uid: Rails.application.credentials.admin[:uid],
    name: Rails.application.credentials.admin[:name],
    email: Rails.application.credentials.admin[:email],
    image: Rails.application.credentials.admin[:image],
    github: Rails.application.credentials.admin[:github],
)


# Settings
Setting.destroy_all

Setting.create(
    key: "social",
    value: ["blog", "hackerrank", "leetcode", "dev.to", "stackoverflow", "codeforces", "medium", "linkedin", "twitter"]
)

Setting.create(
    key: "social_auth",
    value: {
        providers: ["github", "google", "twitter"]
    }
)

Setting.create(
    key: "rate_limiter",
    value: {
        interview_limit_per_day: 100,
        message_limit_per_day: 10,
        reply_limit_per_day: 1000
    }
)



# Tags
Tag.destroy_all
Tag.insert_all!([
    {name: "Rails", group: "frameworks", pos: 1},
    {name: "Sinatra", group: "frameworks", pos: 2},
    {name: "Hanami", group: "frameworks", pos: 2},
    {name: "Ruby", group: "languages", pos: 1},
    {name: "Django", group: "frameworks", pos: 1},
    {name: "Flask", group: "frameworks", pos: 2},
    {name: "Python", group: "languages", pos: 1},
    {name: "Javascript", group: "languages", pos: 1},
    {name: "TypeScript", group: "languages", pos: 1},
    {name: "NodeJs", group: "frameworks", pos: 1},
    {name: "Express", group: "frameworks", pos: 2},
    {name: "React", group: "frameworks", pos: 1},
    {name: "Angular", group: "frameworks", pos: 1},
    {name: "Vue", group: "frameworks", pos: 1},
    {name: "Ember", group: "frameworks", pos: 2},
    {name: "Svelte", group: "frameworks", pos: 3},
    {name: "Gatsby", group: "frameworks", pos: 3},
    {name: "Next.js", group: "frameworks", pos: 3},
    {name: "Html/Css", group: "others", pos: 2},
    {name: "Ionic", group: "frameworks", pos: 4},
    {name: "React-Native", group: "frameworks", pos: 3},
    {name: "Java", group: "languages", pos: 1},
    {name: "Kotlin", group: "languages", pos: 1},
    {name: "Android", group: "others", pos: 1},
    {name: "Spring", group: "frameworks", pos: 1},
    {name: "Struts", group: "frameworks", pos: 4},
    {name: "Stripes", group: "frameworks", pos: 4},
    {name: "Spark", group: "frameworks", pos: 4},
    {name: "Hibernate", group: "frameworks", pos: 3},
    {name: "Dart", group: "languages", pos: 2},
    {name: "Flutter", group: "frameworks", pos: 2},
    {name: "Xamarin", group: "frameworks", pos: 2},
    {name: "PhoneGap", group: "frameworks", pos: 5},
    {name: "Corona", group: "frameworks", pos: 5},
    {name: "Swift", group: "languages", pos: 1},
    {name: "Objective-C", group: "languages", pos: 4},
    {name: "iOS", group: "others", pos: 1},
    {name: "Rust", group: "languages", pos: 2},
    {name: "Go", group: "languages", pos: 1},
    {name: "Elixir", group: "languages", pos: 2},
    {name: "C", group: "languages", pos: 2},
    {name: "C++", group: "languages", pos: 2},
    {name: "C#", group: "languages", pos: 1},
    {name: "Unity", group: "frameworks", pos: 1},
    {name: ".NET", group: "frameworks", pos: 1},
    {name: "PHP", group: "languages", pos: 1},
    {name: "CakePHP", group: "frameworks", pos: 4},
    {name: "CodeIgniter", group: "frameworks", pos: 4},
    {name: "Laravel", group: "frameworks", pos: 1},
    {name: "Symfony", group: "frameworks", pos: 4},
    {name: "Yii", group: "frameworks", pos: 4},
    {name: "Zend", group: "frameworks", pos: 4},
    {name: "Drupal", group: "frameworks", pos: 3},
    {name: "Meteor", group: "frameworks", pos: 4},
    {name: "Joomla", group: "frameworks", pos: 5},
    {name: "Perl", group: "languages", pos: 5},
    {name: "Postgresql", group: "others", pos: 2},
    {name: "MySql", group: "others", pos: 2},
    {name: "MongoDB", group: "others", pos: 3},
    {name: "Oracle", group: "others", pos: 3},
    {name: "Microsoft SQL Server", group: "others", pos: 4},
    {name: "SQLite", group: "others", pos: 4},
    {name: "Redis", group: "others", pos: 3},
    {name: "MariaDB", group: "others", pos: 2},
    {name: "Firebase", group: "others", pos: 3},
    {name: "Elasticsearch", group: "others", pos: 3},
    {name: "SQL", group: "others", pos: 3},
    {name: "AWS", group: "others", pos: 2},
    {name: "R", group: "languages", pos: 4},
    {name: "Carbon", group: "languages", pos: 3},
    {name: "Delphi", group: "languages", pos: 3},
    {name: "Haskell", group: "languages", pos: 3},
    {name: "Julia", group: "languages", pos: 4},
    {name: "Lua", group: "languages", pos: 4},
    {name: "Smalltalk", group: "languages", pos: 3},
    {name: "Scala", group: "languages", pos: 2},
    {name: "Erlang", group: "languages", pos: 2},
    {name: "Lisp", group: "languages", pos: 4},
    {name: "COBOL", group: "languages", pos: 5},
    {name: "Fortran", group: "languages", pos: 5},
    {name: "Assembly", group: "languages", pos: 3},
    {name: "Phoenix", group: "frameworks", pos: 2},
    {name: "Groovy", group: "languages", pos: 4},
    {name: "Grails", group: "frameworks", pos: 4},
    {name: "Kafka", group: "others", pos: 2},
    {name: "Bootstrap", group: "others", pos: 3},
    {name: "Tailwindcss", group: "others", pos: 3},
    {name: "PyTorch", group: "others", pos: 1},
    {name: "TensorFlow", group: "others", pos: 1},
    {name: "Machine Learning", group: "others", pos: 1},
    {name: "Salesforce", group: "others", pos: 2},
    {name: "Blockchain", group: "others", pos: 1},
    {name: "Tester", group: "roles", pos: 1},
    {name: "Computer Programmer", group: "roles", pos: 2},
    {name: "Web Developer", group: "roles", pos: 1},
    {name: "Computer systems engineer", group: "roles", pos: 3},
    {name: "Analyst", group: "roles", pos: 2},
    {name: "Data Scientist", group: "roles", pos: 1},
    {name: "Database Administrator", group: "roles", pos: 3},
    {name: "Database Architect", group: "roles", pos: 3},
    {name: "Database Engineer", group: "roles", pos: 3},
    {name: "QA Engineer", group: "roles", pos: 1},
    {name: "Business Analyst", group: "roles", pos: 1},
    {name: "Network Administrator", group: "roles", pos: 2},
    {name: "Security Analyst", group: "roles", pos: 4},
    {name: "Mobile Developer", group: "roles", pos: 1},
    {name: "Android Developer", group: "roles", pos: 2},
    {name: "iOS Developer", group: "roles", pos: 2},
    {name: "Software Architect", group: "roles", pos: 1},
    {name: "Full Stack Developer", group: "roles", pos: 1},
    {name: "Front End Developer", group: "roles", pos: 1},
    {name: "Back End Developer", group: "roles", pos: 1},
    {name: "Senior Developer", group: "roles", pos: 1},
    {name: "Junior Developer", group: "roles", pos: 1},
    {name: "Entry Developer", group: "roles", pos: 1},
    {name: "Data Engineer", group: "roles", pos: 2},
    {name: "SQL Developer", group: "roles", pos: 4},
    {name: "Game Developer", group: "roles", pos: 1},
    {name: "Embedded Software Engineer", group: "roles", pos: 3},
    {name: "Director of Engineering", group: "roles", pos: 5},
])